-- ============================================================
-- FILE 1: TẠO CẤU TRÚC BẢNG
-- Chạy file này trước tiên trong pgAdmin4 > Query Tool > F5
-- ============================================================
SET client_encoding = 'UTF8';

-- ─── DROP (dọn sạch nếu cần chạy lại) ────────────────────
DROP TRIGGER  IF EXISTS trg_check_pt_position ON "PT_Detail";
DROP FUNCTION IF EXISTS check_pt_position();

DROP TABLE IF EXISTS "CheckInHistory"      CASCADE;
DROP TABLE IF EXISTS "TrainingSession"   CASCADE;
DROP TABLE IF EXISTS "TrainingBooking"   CASCADE;
DROP TABLE IF EXISTS "Feedback"          CASCADE;
DROP TABLE IF EXISTS "Invoice"           CASCADE;
DROP TABLE IF EXISTS "Subscription"      CASCADE;
DROP TABLE IF EXISTS "MembershipPackage" CASCADE;
DROP TABLE IF EXISTS "Equipment"         CASCADE;
DROP TABLE IF EXISTS "Facility"          CASCADE;
DROP TABLE IF EXISTS "ServiceCategory"   CASCADE;
DROP TABLE IF EXISTS "Member"            CASCADE;
DROP TABLE IF EXISTS "PT_Detail"         CASCADE;
DROP TABLE IF EXISTS "Employee"          CASCADE;
DROP TABLE IF EXISTS "AuthRefreshToken"  CASCADE;
DROP TABLE IF EXISTS "Account"           CASCADE;
DROP TABLE IF EXISTS "Role"              CASCADE;

-- ─── TABLES ──────────────────────────────────────────────

CREATE TABLE "Role" (
  "id"        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar NOT NULL
);

CREATE TABLE "Account" (
  "id"             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username"       varchar UNIQUE NOT NULL,
  "password"       varchar NOT NULL,
  "role_id"        int,
  "email"          varchar(255),
  "is_first_login" boolean NOT NULL DEFAULT false
);

CREATE TABLE "AuthRefreshToken" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar UNIQUE NOT NULL,
  "account_id" int NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked_at" timestamp,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- Ghi chú: account_id UNIQUE đảm bảo mỗi account chỉ có đúng 1 Employee
CREATE TABLE "Employee" (
  "id"         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name"  varchar,
  "phone"      varchar,
  "position"   varchar,
  "salary"     decimal,
  "account_id" int UNIQUE,
  "gender"     varchar,
  "dob"        date,
  "email"      varchar,
  "address"    text,
  "avatar"     varchar,
  FOREIGN KEY ("account_id") REFERENCES "Account" ("id") ON DELETE SET NULL
);

CREATE TABLE "PT_Detail" (
  "employee_id"          int PRIMARY KEY,
  "professional_profile" text,
  "body_index"           text,
  "experience_years"     text,
  "achievements"         text,
  "available_schedule"   text,
  FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id") ON DELETE CASCADE
);

-- Ghi chú: account_id UNIQUE đảm bảo mỗi account chỉ có đúng 1 Member,
--          tránh tình trạng tạo duplicate member khi query lỗi
CREATE TABLE "Member" (
  "id"                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name"            varchar,
  "phone"                varchar,
  "email"                varchar,
  "gender"               varchar,
  "dob"                  date,
  "address"              text,
  "account_id"           int UNIQUE,
  "is_active"            boolean DEFAULT true,
  "roadmap_goal"         text,
  "member_free_schedule" text,
  "avatar"               varchar
);

CREATE TABLE "ServiceCategory" (
  "id"                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name"        varchar,
  "benefits_description" text,
  "allowed_gender"       varchar,
  "category_type"        varchar
);

CREATE TABLE "MembershipPackage" (
  "id"            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id"   int,
  "package_name"  varchar,
  "duration_days" int,
  "price"         decimal,
  "is_active"     boolean DEFAULT true,
  "pricing_type"  varchar DEFAULT 'time_based',
  "total_sessions" int
);

CREATE TABLE "Invoice" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id"       int NOT NULL,
  "subscription_id" int,
  "invoice_date"    timestamp DEFAULT CURRENT_TIMESTAMP,
  "total_amount"    decimal NOT NULL,
  "payment_status"  varchar,
  "payment_method"  varchar,
  "notes"           text
);

CREATE TABLE "Subscription" (
  "id"                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id"         int,
  "package_id"        int,
  "registration_date" timestamp,
  "start_date"        date,
  "end_date"          date,
  "status"            varchar,
  "remaining_sessions" int DEFAULT 0
);

CREATE TABLE "Facility" (
  "id"               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facility_name"    varchar,
  "facility_type"    varchar,
  "status"           varchar,
  "description"      text,
  "max_capacity"     int,
  "current_capacity" int DEFAULT 0,
  "amenities"        text,
  CONSTRAINT "check_capacity_limit" CHECK ("current_capacity" <= "max_capacity")
);

CREATE TABLE "Equipment" (
  "id"                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facility_id"          int,
  "equipment_name"       varchar NOT NULL,
  "serial_number"        varchar UNIQUE,
  "quantity"             int DEFAULT 1,
  "status"               varchar,
  "purchase_date"        date,
  "maintenance_deadline" date,
  "origin"               varchar,
  FOREIGN KEY ("facility_id") REFERENCES "Facility" ("id")
);

CREATE TABLE "TrainingBooking" (
  "id"                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id"            int,
  "pt_id"                int,
  "requested_start"      timestamp,
  "requested_end"        timestamp,
  "training_plan_note"   text,
  "status"               varchar,
  "intensity"            varchar,
  "roadmap_goal"         text,
  "member_free_schedule" text,
  "rejection_reason"     text DEFAULT ''
);

CREATE TABLE "TrainingSession" (
  "id"                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id"          int,
  "facility_id"         int,
  "session_time"        timestamp,
  "attendance_status"   varchar,
  "pt_feedback"         text,
  "member_confirmed_at" timestamp,
  "physical_condition"  text,
  "session_result"      text,
  "nutrition_advice"    text
);

CREATE TABLE "CheckInHistory" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id"       int,
  "facility_id"     int,
  "check_in_time"   timestamp DEFAULT CURRENT_TIMESTAMP,
  "booking_id"      int
);

CREATE TABLE "Feedback" (
  "id"              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id"       int,
  "processor_id"    int,
  "equipment_id"    int,
  "content"         text,
  "sent_at"         timestamp,
  "resolution_note" text,
  "status"          varchar,
  "rating"          int CHECK ("rating" >= 1 AND "rating" <= 5)
);
