CREATE TABLE "Role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar NOT NULL
);

CREATE TABLE "Account" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role_id" int
);

CREATE TABLE "AuthRefreshToken" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar UNIQUE NOT NULL,
  "account_id" int NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked_at" timestamp,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Employee" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "phone" varchar, 
  "position" varchar,
  "salary" decimal,
  "account_id" int, -- Để trống (NULL) được
  "gender" varchar,
  "dob" date,
  "email" varchar,
  "address" text,
  FOREIGN KEY ("account_id") REFERENCES "Account" ("id") ON DELETE SET NULL
);

CREATE TABLE "PT_Detail" (
  "employee_id" int PRIMARY KEY,
  "professional_profile" text,
  "body_index" text,
  "experience_years" text,
  "achievements" text,
  "available_schedule" text,
  FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id") ON DELETE CASCADE
);

CREATE TABLE "Member" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "phone" varchar,
  "email" varchar,
  "gender" varchar,
  "dob" date,
  "address" text,
  "account_id" int,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "ServiceCategory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar,
  "benefits_description" text,
  "allowed_gender" varchar
);

CREATE TABLE "MembershipPackage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "package_name" varchar,
  "duration_days" int,
  "price" decimal,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "Invoice" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int NOT NULL,
  "subscription_id" int,
  "invoice_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "total_amount" decimal NOT NULL,
  "payment_status" varchar,
  "payment_method" varchar,
  "notes" text
);

CREATE TABLE "Subscription" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int,
  "package_id" int,
  "registration_date" timestamp,
  "start_date" date,
  "end_date" date,
  "status" varchar
);

CREATE TABLE "Facility" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facility_name" varchar,
  "facility_type" varchar,
  "status" varchar,
  "description" text,
  "max_capacity" int,
  "current_capacity" int DEFAULT 0,
  "amenities" text,
  CONSTRAINT "check_capacity_limit" CHECK ("current_capacity" <= "max_capacity")
);

CREATE TABLE "Equipment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "facility_id" int,
  "equipment_name" varchar NOT NULL,
  "serial_number" varchar UNIQUE,
  "quantity" int DEFAULT 1,
  "status" varchar,
  "purchase_date" date,
  "maintenance_deadline" date, -- Dùng chung cho cả hạn bảo hành/bảo trì
  "origin" varchar,
  FOREIGN KEY ("facility_id") REFERENCES "Facility" ("id")
);

CREATE TABLE "TrainingBooking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int,
  "pt_id" int,
  "requested_start" timestamp,
  "requested_end" timestamp,
  "training_plan_note" text,
  "status" varchar
);

CREATE TABLE "TrainingSession" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "facility_id" int,
  "session_time" timestamp,
  "attendance_status" varchar,
  "pt_feedback" text
);


  CREATE TABLE "Feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" int,
  "processor_id" int,
  "equipment_id" int,
  "content" text,
  "sent_at" timestamp,
  "resolution_note" text,
  "status" varchar,
  "rating" int CHECK ("rating" >= 1 AND "rating" <= 5)
);


COMMENT ON COLUMN "Role"."role_name" IS 'OWNER, MANAGER, PT, MEMBER';

COMMENT ON COLUMN "Employee"."position" IS 'SALE, CS_STAFF, PT, MANAGER';

COMMENT ON COLUMN "ServiceCategory"."category_name" IS 'VIP, Normal, Female-only';

COMMENT ON COLUMN "Subscription"."status" IS 'Active, Paused, Expired, Transferred';

COMMENT ON COLUMN "Facility"."status" IS 'Operating, Maintenance';

COMMENT ON COLUMN "Equipment"."status" IS 'New, Old, Broken';

COMMENT ON COLUMN "TrainingBooking"."status" IS 'Pending, Accepted, Rejected';

COMMENT ON COLUMN "TrainingSession"."attendance_status" IS 'Present, Absent';

COMMENT ON COLUMN "Feedback"."status" IS 'Pending, Resolved';

CREATE INDEX "idx_auth_refresh_token_account_id" ON "AuthRefreshToken" ("account_id");

CREATE INDEX "idx_auth_refresh_token_expires_at" ON "AuthRefreshToken" ("expires_at");

COMMENT ON COLUMN "MembershipPackage"."is_active" IS 'true: Active, false: Disabled';

COMMENT ON COLUMN "Invoice"."payment_status" IS 'Pending, Paid, Cancelled';

COMMENT ON COLUMN "Invoice"."payment_method" IS 'Cash, Card, Bank Transfer';

ALTER TABLE "Account" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuthRefreshToken" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Employee" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PT_Detail" ADD FOREIGN KEY ("employee_id") REFERENCES "Employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Member" ADD FOREIGN KEY ("account_id") REFERENCES "Account" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MembershipPackage" ADD FOREIGN KEY ("category_id") REFERENCES "ServiceCategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Subscription" ADD FOREIGN KEY ("member_id") REFERENCES "Member" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Subscription" ADD FOREIGN KEY ("package_id") REFERENCES "MembershipPackage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Equipment" ADD FOREIGN KEY ("facility_id") REFERENCES "Facility" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TrainingBooking" ADD FOREIGN KEY ("member_id") REFERENCES "Member" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TrainingBooking" ADD FOREIGN KEY ("pt_id") REFERENCES "PT_Detail" ("employee_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TrainingSession" ADD FOREIGN KEY ("booking_id") REFERENCES "TrainingBooking" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TrainingSession" ADD FOREIGN KEY ("facility_id") REFERENCES "Facility" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Feedback" ADD FOREIGN KEY ("member_id") REFERENCES "Member" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Feedback" ADD FOREIGN KEY ("processor_id") REFERENCES "Employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Feedback" ADD FOREIGN KEY ("equipment_id") REFERENCES "Equipment" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Invoice" ADD FOREIGN KEY ("member_id") REFERENCES "Member" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Invoice" ADD FOREIGN KEY ("subscription_id") REFERENCES "Subscription" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE OR REPLACE FUNCTION check_pt_position()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "Employee" WHERE "id" = NEW.employee_id AND "position" = 'PT') THEN
        RAISE EXCEPTION 'Chỉ nhân viên có vị trí là PT mới được thêm vào bảng PT_Detail';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_pt_position
BEFORE INSERT OR UPDATE ON "PT_Detail"
FOR EACH ROW EXECUTE FUNCTION check_pt_position();