CREATE TABLE IF NOT EXISTS "AuthRefreshToken" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token_hash" varchar UNIQUE NOT NULL,
  "account_id" int NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked_at" timestamp,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_auth_refresh_token_account_id" ON "AuthRefreshToken" ("account_id");

CREATE INDEX IF NOT EXISTS "idx_auth_refresh_token_expires_at" ON "AuthRefreshToken" ("expires_at");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'auth_refresh_token_account_id_fkey'
  ) THEN
    ALTER TABLE "AuthRefreshToken"
      ADD CONSTRAINT "auth_refresh_token_account_id_fkey"
      FOREIGN KEY ("account_id") REFERENCES "Account" ("id") DEFERRABLE INITIALLY IMMEDIATE;
  END IF;
END;
$$;
 